name: Tests
on : [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v4
        with:
          go-version: 1.25
      - run: go test -v ./...
      - run: go test -cover ./...